import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./_components/nav/SideNav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-background flex min-h-screen overflow-hidden text-white">
        <TRPCReactProvider>
          <SideNav />
          <main className="flex flex-1">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
